# Generated by Django 5.1.4 on 2024-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Campaign"),
                            ("video", "Video Campaign"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("file", models.FileField(upload_to="campaigns/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
