# Generated by Django 5.1.4 on 2024-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="campaigns/images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="campaigns/logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TargetDemographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="price",
            new_name="budget",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="name",
        ),
        migrations.AddField(
            model_name="campaign",
            name="bidding",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="bidding_focus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="business_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="final_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_optimize",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_people",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="campaigns/videos/"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="campaign_images", to="api.campaignimage"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="logos",
            field=models.ManyToManyField(
                blank=True, related_name="campaign_logos", to="api.campaignlogo"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="campaign_keywords", to="api.keyword"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_demographics",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaign_demographics",
                to="api.targetdemographic",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="campaign_topics", to="api.topic"
            ),
        ),
    ]
