# Generated by Django 5.0.6 on 2025-01-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_citydata_alter_campaign_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=254)),
                ("state", models.CharField(max_length=254)),
                ("city", models.CharField(max_length=254)),
                ("tier", models.CharField(max_length=254)),
                ("population", models.CharField(max_length=254)),
            ],
        ),
    ]
