# Generated by Django 5.0.6 on 2025-01-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="bidding",
            new_name="age",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="bidding_focus",
            new_name="carrier",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="business_name",
            new_name="day_part",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="final_url",
            new_name="device",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="geo_location",
            new_name="device_price",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="target_content",
            new_name="environment",
        ),
        migrations.RenameField(
            model_name="campaign",
            old_name="target_people",
            new_name="exchange_selection",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="campaign_type",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="file",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="target_optimize",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="text",
        ),
        migrations.AddField(
            model_name="campaign",
            name="geo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="interset",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="proximity",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="proximity_store",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="weather",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
