# Generated by Django 5.0.6 on 2025-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_bidding_campaign_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="geo",
        ),
        migrations.AddField(
            model_name="campaign",
            name="location",
            field=models.ManyToManyField(
                blank=True, related_name="Location", to="api.location"
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="age",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="device",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="environment",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
