# Generated by Django 5.0.6 on 2025-01-14 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_campaign_geo_campaign_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="keyword",
        ),
        migrations.AddField(
            model_name="keyword",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="campaign_keywords/"
            ),
        ),
        migrations.AddField(
            model_name="keyword",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
