# Generated by Django 5.0.6 on 2025-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_campaign_target_demographics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="interset",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
